apiVersion: jenkins.io/v1
kind: Environment
metadata:
  creationTimestamp: null
  name: production
spec:
  cluster: 34.76.244.53.nip.io
  kind: Permanent
  label: Production
  namespace: jx-production
  order: 200
  previewGitInfo:
    user: {}
  promotionStrategy: Manual
  source:
    ref: master
    url: https://github.com/core-platform-test-org/environment-speakergem-production.git
  teamSettings: {}
status: {}
