dependencies:
- alias: tekton
  name: tekton
  repository: http://chartmuseum.jenkins-x.io
  version: 0.0.33
- alias: prow
  name: prow
  repository: http://chartmuseum.jenkins-x.io
  version: 0.0.470
- name: jenkins-x-platform
  repository: http://chartmuseum.jenkins-x.io
  version: 0.0.3832
